-- DESIGN HUB V6.2 — HISTORIAL GENERAL
-- Cada INSERT, UPDATE o DELETE de tasks queda registrado en task_change_history.
create table if not exists public.task_change_history (
 id bigint generated by default as identity primary key,
 task_id text not null,
 operation text not null check (operation in ('INSERT','UPDATE','DELETE')),
 before_data jsonb,
 after_data jsonb,
 changed_by uuid references public.profiles(id) on delete set null,
 created_at timestamptz not null default now()
);
create index if not exists task_change_history_created_idx on public.task_change_history(created_at desc);
create index if not exists task_change_history_task_created_idx on public.task_change_history(task_id,created_at desc);
alter table public.task_change_history enable row level security;
drop policy if exists "Authenticated users can read task history" on public.task_change_history;
create policy "Authenticated users can read task history" on public.task_change_history for select to authenticated using (true);
revoke insert,update,delete on public.task_change_history from anon,authenticated;
grant select on public.task_change_history to authenticated;
create or replace function public.log_task_change() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if tg_op='INSERT' then
  insert into public.task_change_history(task_id,operation,before_data,after_data,changed_by) values(new.id::text,'INSERT',null,to_jsonb(new),auth.uid()); return new;
 elsif tg_op='UPDATE' then
  insert into public.task_change_history(task_id,operation,before_data,after_data,changed_by) values(new.id::text,'UPDATE',to_jsonb(old),to_jsonb(new),auth.uid()); return new;
 elsif tg_op='DELETE' then
  insert into public.task_change_history(task_id,operation,before_data,after_data,changed_by) values(old.id::text,'DELETE',to_jsonb(old),null,auth.uid()); return old;
 end if; return null;
end; $$;
drop trigger if exists trg_tasks_change_history on public.tasks;
create trigger trg_tasks_change_history after insert or update or delete on public.tasks for each row execute function public.log_task_change();
